services:
  - type: web
    name: rahman-portfolio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: DEPLOY_TARGET
        value: render
      - key: NODE_ENV
        value: production
    routes:
      - path: /*
        destination: /index.html
        match: miss
